export const projectsData = [
  {
    id: 1,
    title: "eyCommerce",
    description: `En este proyecto me centré en el diseño de la pagina, la cual es responsive.
    Utilicé React para la visualización, react router para la navegación, tailwind para los estilos`,
    image: "/image/projects/Shopi-App.png",
    gitUrl: "https://github.com/nahwish/EyCommerce",
    tag: ["All", "Web", "Javascript", "React", "Tailwind"],
    previewUrl: "/",
    hashtag: ["#Javascript", "#React", "#Tailwind", "#ContextApi"],
  },

  {
    id: 2,
    title: "Anotación de Tareas",
    description: ` Esta aplicación fullstack permite a los usuarios registrar sus notas personales y acceder a ellas al iniciar sesión con una cuenta previamente creada. Además, brinda la opción de editar las notas y marcarlas como tareas diarias completadas. Fue desarrollada utilizando NodeJS + Express como servidor backend, PostgreSQL como base de datos y React como frontend.`,
    image: "/image/projects/Todo-App.png",
    gitUrl: "https://github.com/nahwish/Todo-App",
    tag: ["All", "Web", "React", "CSS", "Express", "Posgres", "Node"],
    previewUrl: "/",
    hashtag: [
      "#Javascript",
      "#React",
      "#CSS",
      "#Express",
      "#Posgres",
      "#Nodejs",
      "#React-cookie",
    ],
  },
  {
    id: 3,
    title: "Travel App",
    description: " una descripcón lore ipsum",
    image: "/image/projects/Travel-App.png",
    gitUrl: "https://github.com/nahwish/matchpoint",
    tag: ["All", "Web", "Tailwind", "React", "TypeScript", "Javascript"],
    previewUrl: "/",
    hashtag: ["#Javascript", "#React", "#Tailwind", "#TypeScript"],
  },
  {
    id: 4,
    title: "Funny Crash",
    description: " una descripcón lore ipsum",
    image: "/image/projects/Funny-Crash.png",
    gitUrl: "/",
    tag: ["All", "Game", "C#", "Unity"],
    previewUrl: "/",
    hashtag: ["#CSharp", "#Unity", "#Game"],
  },
  {
    id: 5,
    title: "Labyrinth",
    description: " una descripcón lore ipsum",
    image: "/image/projects/labyrinth.png",
    gitUrl: "/",
    tag: ["All", "Game", "C#", "Unity"],
    previewUrl: "/",
    hashtag: ["#CSharp", "#Unity", "#Game"],
  },
];